# WriteObfKey.cmake -- regenerates ObfKey.generated.h on every build.
#
# Invoked as:
#   cmake -DOUT_HEADER=<path> -P WriteObfKey.cmake
#
# Produces a header containing a fresh 64-bit random seed plus a per-symbol
# mask. Because `string(RANDOM ...)` re-rolls every CMake invocation, every
# build of the loader sees different constants, which in turn scrambles
# every OBF("...") literal in the binary.

if(NOT DEFINED OUT_HEADER)
    message(FATAL_ERROR "WriteObfKey.cmake requires -DOUT_HEADER=<path>")
endif()

set(ALPHABET "0123456789abcdef")

string(RANDOM LENGTH 16 ALPHABET "${ALPHABET}" SEED_HEX)
string(RANDOM LENGTH 16 ALPHABET "${ALPHABET}" MASK_HEX)
string(RANDOM LENGTH  8 ALPHABET "${ALPHABET}" TRAP_HEX)
string(TIMESTAMP BUILD_STAMP "%Y-%m-%dT%H:%M:%SZ" UTC)

set(NEW_CONTENT
"// Auto-generated by cmake/WriteObfKey.cmake. Do NOT edit by hand.
// Regenerated on every build, so obfuscated literals differ per binary.
#pragma once

#define HKED_OBF_BUILD_STAMP \"${BUILD_STAMP}\"
#define HKED_OBF_SEED        0x${SEED_HEX}ULL
#define HKED_OBF_MASK        0x${MASK_HEX}ULL
#define HKED_TRAP_SEED       0x${TRAP_HEX}UL
")

# Only rewrite the file if the content actually changed, so we do not force
# a rebuild when nothing security-relevant moved.
if(EXISTS "${OUT_HEADER}")
    file(READ "${OUT_HEADER}" OLD_CONTENT)
    if(OLD_CONTENT STREQUAL NEW_CONTENT)
        return()
    endif()
endif()

file(WRITE "${OUT_HEADER}" "${NEW_CONTENT}")
message(STATUS "Regenerated obfuscation key: ${OUT_HEADER}")
