// Obfuscate.h -- compile-time string obfuscation.
//
// Every literal wrapped in OBF("...") lands in the binary as XOR-encrypted
// bytes and is decrypted into a stack buffer on first access. The XOR key
// is seeded by HKED_OBF_SEED, which is regenerated by CMake on every build
// (see cmake/WriteObfKey.cmake), so the exact byte pattern in .rdata is
// different for every compilation.
//
// Cost: one 16-byte buffer per obfuscated literal per call site, a handful
// of xor+rol instructions, no heap.
//
// Limitations: this is not actual crypto. A determined reverse engineer
// can dump the decrypted strings at runtime. It is deliberately cheap --
// its purpose is to keep grep-able constants ("debugger", "cheat", ...)
// out of the raw binary.

#pragma once

#include "ObfKey.generated.h"

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <string>

namespace hked::obf {

// Rotate-left on a 64-bit value -- constexpr in C++17.
constexpr uint64_t Rotl(uint64_t v, unsigned r) {
    return (v << (r & 63)) | (v >> ((64 - (r & 63)) & 63));
}

// A cheap but non-trivial compile-time PRNG (SplitMix64 variant). Seeded per
// call site with (HKED_OBF_SEED ^ line ^ counter) so two identical string
// literals at different locations use different keystreams.
constexpr uint64_t NextKey(uint64_t state) {
    uint64_t z = state + 0x9E3779B97F4A7C15ULL;
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
    return z ^ (z >> 31);
}

template <std::size_t N>
struct Buffer {
    unsigned char data[N];
};

template <std::size_t N>
constexpr Buffer<N> Encrypt(const char (&s)[N], uint64_t seed) {
    Buffer<N> out{};
    uint64_t state = seed;
    for (std::size_t i = 0; i < N; ++i) {
        state          = NextKey(state);
        uint8_t k      = static_cast<uint8_t>(state ^ (state >> 17) ^ (state >> 41));
        out.data[i]    = static_cast<unsigned char>(s[i]) ^ k;
    }
    return out;
}

// Runtime holder: stores the ciphertext on the stack and decrypts lazily.
template <std::size_t N>
class Obfuscated {
public:
    constexpr Obfuscated(const char (&s)[N], uint64_t seed)
        : buf_(Encrypt(s, seed)), seed_(seed) {}

    // Decrypts into the provided scratch buffer and returns a pointer to it.
    // The scratch buffer must have at least N bytes.
    const char* decrypt_into(char* scratch) const noexcept {
        uint64_t state = seed_;
        for (std::size_t i = 0; i < N; ++i) {
            state       = NextKey(state);
            uint8_t k   = static_cast<uint8_t>(state ^ (state >> 17) ^ (state >> 41));
            scratch[i]  = static_cast<char>(buf_.data[i] ^ k);
        }
        return scratch;
    }

    std::string decrypt() const {
        std::string out(N - 1, '\0');
        uint64_t state = seed_;
        for (std::size_t i = 0; i < N; ++i) {
            state    = NextKey(state);
            uint8_t k = static_cast<uint8_t>(state ^ (state >> 17) ^ (state >> 41));
            char c    = static_cast<char>(buf_.data[i] ^ k);
            if (i + 1 < N) out[i] = c;
        }
        return out;
    }

    constexpr std::size_t size() const noexcept { return N; }

private:
    Buffer<N> buf_;
    uint64_t  seed_;
};

template <std::size_t N>
constexpr Obfuscated<N> Make(const char (&s)[N], uint64_t seed) {
    return Obfuscated<N>(s, seed);
}

} // namespace hked::obf

// Mangle the per-use seed with __LINE__ + __COUNTER__ so identical literals
// pick different keystreams.
#define HKED_OBF_SEED_HERE \
    (HKED_OBF_SEED ^ (static_cast<uint64_t>(__LINE__) * 0xA24BAED4963EE407ULL) \
                   ^ (static_cast<uint64_t>(__COUNTER__) * 0x9FB21C651E98DF25ULL) \
                   ^ HKED_OBF_MASK)

// Decrypt-on-call wrapper. Usage:
//     const char* msg = OBF("Hello world");
// The decrypted string lives in a stack buffer tied to a *named* scope.
// For one-shot use, prefer OBFS(...) which yields a std::string rvalue.
#define OBF(lit)                                                              \
    ([]() -> const char* {                                                    \
        static constexpr auto _o =                                            \
            ::hked::obf::Make(lit, HKED_OBF_SEED_HERE);                       \
        thread_local char _scratch[_o.size()];                                \
        return _o.decrypt_into(_scratch);                                     \
    }())

#define OBFS(lit)                                                             \
    ([]() -> std::string {                                                    \
        static constexpr auto _o =                                            \
            ::hked::obf::Make(lit, HKED_OBF_SEED_HERE);                       \
        return _o.decrypt();                                                  \
    }())

// Use OBF("...") with narrow string literals. For wide-char comparisons
// (e.g. window class names) decrypt with OBFS then widen with MultiByteToWideChar
// at the call site, or keep the comparison case-insensitive on the A-suffixed
// Win32 API (FindWindowA, CreateToolhelp32Snapshot + PROCESSENTRY32W names
// converted with WideCharToMultiByte).
